#!/usr/bin/env node
"use strict";

var co = require("co");
var Argparse = require("argparse").ArgumentParser;
var gencConf = require("./package.json");
var Genc = require(".");
var debug = require("debug")("genc");
var Log = require("log");
var log = new Log();

var app = new Genc();

co(function*() {
    var parser = new Argparse({
        version: gencConf.version,
        addHelp: true,
        description: "genc - static site generator"
    });

    var subparser = parser.addSubparsers({
        title: "subcommands",
        dest: "command"
    });

    var newPost = subparser.addParser("new", {addHelp: true, help: "new help"});
    newPost.addArgument(
        ["title"],
        {
            help: "Title of page."
        }
    );
    newPost.addArgument(
        ["-t", "--tags"],
        {
            action: "store",
            help: "Creates a new page or post."
        }
    );

    subparser.addParser("config", {addHelp: true, help: "Print a autogenerated configuration."});
    subparser.addParser("build", {addHelp: true, help: "Build your site."});

    var args = parser.parseArgs();
    if(args.command === "new"){
        yield app.newPost(args.title, args.tags);
    }
    if (args.command === "config"){
        log.info("Default config: %s", app.config());
    }
    if (args.command === "build"){
        yield app.generate();
    }
}).catch(function(e) {
    debug(e);
});
